### PR TITLE
added file : temperature calculator

### PR DESCRIPTION
**Pull request by ghost**
Added a new file (to convert temperature from Fahrenheit to Celsius and  vice versa). The code is all about aesthetic design.

### CODE REVIEW

**Comment by ghost** [comment]
It would be really nice of you to review my code and provide me with some insightful corrections and naming conventions :)

**Comment by Samuel-de-Oliveira** [comment]
@The-Young-Programmer Please can you check this pull request?

**Comment by The-Young-Programmer** [comment]
@Easter-Maxwell-01 Great job! I did some checking, and I notice this error `#include <iomanip> not found`
I'm using **Code Blocks** compiler. 
I'm having trouble getting the error message to go away, though. I've tried different methods.
Do you have any ideas as to what might be causing this?


@Samuel-de-Oliveira I really appreciate what you did. You did a great job! Sorry for late reply.

**Comment by ghost** [comment]
> @Easter-Maxwell-01 Great job! I did some checking, and I notice this error `#include <iomanip> not found` I'm using **Code Blocks** compiler. I'm having trouble getting the error message to go away, though. I've tried different methods. Do you have any ideas as to what might be causing this?
> 
> @Samuel-de-Oliveira I really appreciate what you did. You did a great job! Sorry for late reply.

@The-Young-Programmer Thank you very much for your reply. About the '#include <iomanip> not found' error, have you tried naming your file as a .cpp file rather than a .c? And also make sure you are compiling the program in a C++ enabled environment.

**Comment by ghost** [comment]
@The-Young-Programmer I use the Visual Studio IDE just in case you're wondering...

**Comment by The-Young-Programmer** [comment]
> > @Easter-Maxwell-01 Great job! I did some checking, and I notice this error `#include <iomanip> not found` I'm using **Code Blocks** compiler. I'm having trouble getting the error message to go away, though. I've tried different methods. Do you have any ideas as to what might be causing this?
> > @Samuel-de-Oliveira I really appreciate what you did. You did a great job! Sorry for late reply.
> 
> @The-Young-Programmer Thank you very much for your reply. About the '#include not found' error, have you tried naming your file as a .cpp file rather than a .c? And also make sure you are compiling the program in a C++ enabled environment.


@Easter-Maxwell-01 Thanks for your feedback! It's working just fine. I use code blocks.

**Pull request merged**
